apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: minnietask-cpu2
  name: minnietask-cpu2
spec:
  replicas: 20
  selector:
    matchLabels:
      run: minnietask-cpu2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: minnietask-cpu2
    spec:
      containers:
        - image: fcollman/minnietask:v21
          name: minnietask-cpu2
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            [
              "-c",
              "while true; do python -u worker.py https://sqs.us-west-2.amazonaws.com/629034007606/forrest 240; done",
            ]
          env:
            - name: CLOUDSDK_CORE_PROJECT
              value: ${CLOUDSDK_CORE_PROJECT}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/root/.cloudvolume/secrets/google-secret.json"
            - name: BUMP
              value: "test2"
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          volumeMounts:
            - name: secrets
              mountPath: /root/.cloudvolume/secrets
              readOnly: true
            - name: boto
              mountPath: /root/.boto
              readOnly: true
              subPath: minimal_boto
      dnsPolicy: Default
      volumes:
        - name: secrets
          secret:
            secretName: secretsminnie
        - name: boto
          secret:
            secretName: boto
